/* =============================================================
   tools-data.js — Weston College Assistive Technology Guide
   Single source of truth for all tool content.
   Edit here; both staff.html and student.html reflect changes.
   ============================================================= */

const TOOLS_DATA = [

  // ─── WINDOWS / DELL ──────────────────────────────────────────

  { id:'narrator', platform:'windows', cats:['vision'],
    name:'Narrator',
    staffDesc:'Built-in Windows screen reader. Reads menus, documents, and websites aloud with keyboard navigation. Useful for blind or visually impaired users, dyslexia support, and reading fatigue.',
    studentDesc:'Windows reads everything on the screen aloud for you — menus, documents, websites, everything. Great if reading is tiring or difficult.',
    staffWhere:'Settings → Accessibility → Narrator',
    studentWhere:'Open Settings, choose Accessibility, then tap Narrator',
    shortcut:'Ctrl + Windows + Enter', lwb:true, icon:'speaker',
    ytStaff:'Windows Narrator screen reader tutorial educator',
    ytStudent:'Windows Narrator how to use for students' },

  { id:'magnifier', platform:'windows', cats:['vision'],
    name:'Magnifier',
    staffDesc:'Enlarges part or all of the screen. Full-screen, lens, or docked modes. Useful for low vision, reading small print, or classroom display work.',
    studentDesc:'Makes everything on screen bigger — like a magnifying glass for your computer. You can zoom in on just one part or the whole screen.',
    staffWhere:'Settings → Accessibility → Magnifier',
    studentWhere:'Open Settings, choose Accessibility, then Magnifier',
    shortcut:'Windows + Plus (+)', lwb:false, icon:'zoom',
    ytStaff:'Windows Magnifier accessibility tutorial',
    ytStudent:'Windows Magnifier zoom in how to use' },

  { id:'text-size', platform:'windows', cats:['vision'],
    name:'Text size and display scaling',
    staffDesc:'Increases text size globally across all apps via a slider. No restart required. Separate from browser zoom — affects the whole operating system.',
    studentDesc:'Makes all the words on your screen bigger everywhere — not just in one app. Slide it up until it feels comfortable.',
    staffWhere:'Settings → Accessibility → Text size',
    studentWhere:'Open Settings, choose Accessibility, then Text size',
    shortcut:null, lwb:false, icon:'type',
    ytStaff:'Windows 11 text size display scaling tutorial',
    ytStudent:'Windows make text bigger how to' },

  { id:'contrast-themes', platform:'windows', cats:['vision','cognitive'],
    name:'Contrast themes',
    staffDesc:'High-contrast OS-level colour modes. Four built-in options, fully customisable. Reduces visual noise and improves text/background separation across all applications.',
    studentDesc:'Changes your screen colours so everything stands out more clearly. Really helpful if your eyes get tired looking at bright white screens.',
    staffWhere:'Settings → Accessibility → Contrast themes',
    studentWhere:'Open Settings, choose Accessibility, then Contrast themes',
    shortcut:'Left Alt + Left Shift + Print Screen', lwb:false, icon:'contrast',
    ytStaff:'Windows high contrast themes accessibility tutorial',
    ytStudent:'Windows high contrast mode turn on' },

  { id:'colour-filters', platform:'windows', cats:['vision'],
    name:'Colour filters',
    staffDesc:'OS-level colour blindness support. Modes include red/green (protanopia/deuteranopia), blue/yellow (tritanopia), and full greyscale. Toggleable via keyboard shortcut.',
    studentDesc:'Changes the colours on your screen if some colours are hard for you to tell apart. Works for different types of colour blindness.',
    staffWhere:'Settings → Accessibility → Colour filters',
    studentWhere:'Open Settings, choose Accessibility, then Colour filters',
    shortcut:'Windows + Ctrl + C', lwb:true, icon:'palette',
    ytStaff:'Windows colour filters colour blindness accessibility',
    ytStudent:'Windows colour filters colour blindness how to turn on' },

  { id:'live-captions-win', platform:'windows', cats:['hearing'],
    name:'Live Captions',
    staffDesc:'Real-time on-screen captions for all audio on the device — video, meetings, calls. Processed on-device for privacy. Works offline. Accessible via keyboard shortcut.',
    studentDesc:'Shows you the words as someone speaks — on any video, in any meeting, from any app. You can read along with what\'s being said.',
    staffWhere:'Settings → Accessibility → Captions',
    studentWhere:'Open Settings, choose Accessibility, then Captions',
    shortcut:'Windows + Ctrl + L', lwb:true, icon:'captions',
    ytStaff:'Windows 11 Live Captions tutorial',
    ytStudent:'Windows Live Captions how to turn on subtitles' },

  { id:'mono-audio', platform:'windows', cats:['hearing'],
    name:'Mono audio',
    staffDesc:'Combines stereo left and right channels into a single channel. Essential for users with single-sided deafness or significant hearing loss in one ear.',
    studentDesc:'If you can only hear well in one ear, this makes sure you don\'t miss sounds that would normally only play in the other ear.',
    staffWhere:'Settings → Accessibility → Audio',
    studentWhere:'Open Settings, choose Accessibility, then Audio',
    shortcut:null, lwb:false, icon:'headphones',
    ytStaff:'Windows mono audio hearing accessibility tutorial',
    ytStudent:'Windows mono audio one ear hearing' },

  { id:'visual-alerts', platform:'windows', cats:['hearing'],
    name:'Visual alerts',
    staffDesc:'Replaces audio system alerts with visible screen or window flashes. Configurable per alert type. Useful when audio is not available or appropriate.',
    studentDesc:'Instead of playing a sound to get your attention, the screen flashes. Useful if you\'re wearing headphones or can\'t hear alert sounds.',
    staffWhere:'Settings → Accessibility → Audio',
    studentWhere:'Open Settings, choose Accessibility, then Audio',
    shortcut:null, lwb:false, icon:'bell',
    ytStaff:'Windows visual alerts flash screen accessibility',
    ytStudent:'Windows flash alerts for sounds how to' },

  { id:'voice-access', platform:'windows', cats:['motor','writing'],
    name:'Voice Access',
    staffDesc:'Full voice control of the operating system. Navigate menus, click buttons, open applications, and dictate text without keyboard or mouse. Numbers overlay labels interactive elements.',
    studentDesc:'Control your whole computer with your voice — open apps, click things, type words. Say "click 3" to tap whatever is labelled 3 on screen.',
    staffWhere:'Settings → Accessibility → Speech → Voice Access',
    studentWhere:'Open Settings, choose Accessibility, then Speech',
    shortcut:null, lwb:true, icon:'mic',
    ytStaff:'Windows Voice Access full control tutorial',
    ytStudent:'Windows Voice Access hands free computer tutorial' },

  { id:'voice-typing-win', platform:'windows', cats:['motor','writing'],
    name:'Voice Typing',
    staffDesc:'Speech-to-text in any text field across all applications. Auto-punctuation included. Activate with keyboard shortcut — no app switching required.',
    studentDesc:'Speak and watch your words appear. Works in any text box — emails, documents, assignments. Just press the shortcut and start talking.',
    staffWhere:'Any text field on Windows',
    studentWhere:'Click anywhere you want to type, then use the shortcut',
    shortcut:'Windows + H', lwb:false, icon:'mic',
    ytStaff:'Windows Voice Typing dictation tutorial all apps',
    ytStudent:'Windows speak to type tutorial students' },

  { id:'on-screen-keyboard', platform:'windows', cats:['motor'],
    name:'On-screen keyboard',
    staffDesc:'Full software keyboard controlled by mouse, touch, or eye tracking. Includes word prediction and text completion to reduce key presses. Alternative input for motor impairments.',
    studentDesc:'A keyboard that appears on screen — use your mouse or touch to press the keys. Helpful if a physical keyboard is difficult to use.',
    staffWhere:'Settings → Accessibility → Keyboard',
    studentWhere:'Open Settings, choose Accessibility, then Keyboard',
    shortcut:null, lwb:false, icon:'keyboard',
    ytStaff:'Windows on-screen keyboard tutorial accessibility',
    ytStudent:'Windows on-screen keyboard how to use' },

  { id:'eye-control', platform:'windows', cats:['motor'],
    name:'Eye Control',
    staffDesc:'Full PC control using eye-tracking hardware (e.g. Tobii). Navigate, type, and scroll without hands. Requires compatible tracking device.',
    studentDesc:'Move your eyes to control your computer. Needs a special camera that tracks where you\'re looking — ask your support team about getting one.',
    staffWhere:'Settings → Accessibility → Eye Control',
    studentWhere:'Open Settings, choose Accessibility, then Eye Control',
    shortcut:null, lwb:false, icon:'eye',
    ytStaff:'Windows Eye Control eye tracking tutorial',
    ytStudent:'Windows Eye Control how does it work' },

  { id:'focus-mode', platform:'windows', cats:['cognitive'],
    name:'Focus and notification settings',
    staffDesc:'System-level distraction reduction. Suppress notifications during sessions. Set timed focus blocks with break reminders. Integrates with Clock app for Pomodoro-style sessions.',
    studentDesc:'Stops your computer from interrupting you with pop-ups while you\'re trying to work. Set a timer and your device stays quiet until you\'re done.',
    staffWhere:'Settings → System → Focus',
    studentWhere:'Open Settings, choose System, then Focus',
    shortcut:null, lwb:false, icon:'focus',
    ytStaff:'Windows Focus Sessions notifications tutorial',
    ytStudent:'Windows Focus mode stop distractions study' },

  // ─── IPAD ────────────────────────────────────────────────────

  { id:'voiceover', platform:'ipad', cats:['vision'],
    name:'VoiceOver',
    staffDesc:'iPadOS built-in screen reader. Navigation via swipe gestures. Works across all installed apps. Essential for blind users; also supports low vision and dyslexia.',
    studentDesc:'Your iPad reads everything out loud — apps, messages, web pages. Swipe to move between things and double-tap to open them.',
    staffWhere:'Settings → Accessibility → VoiceOver',
    studentWhere:'Open Settings, choose Accessibility, then VoiceOver',
    shortcut:null, lwb:true, icon:'speaker',
    ytStaff:'iPad VoiceOver screen reader tutorial educator',
    ytStudent:'iPad VoiceOver how to use for beginners' },

  { id:'ipad-zoom', platform:'ipad', cats:['vision'],
    name:'Zoom (iPad)',
    staffDesc:'Screen magnification via three-finger double-tap. Full-screen or floating window mode. Follows focus automatically. Works alongside VoiceOver.',
    studentDesc:'Double-tap with three fingers to zoom in on any part of the screen. You can move the zoomed view around while staying in your app.',
    staffWhere:'Settings → Accessibility → Zoom',
    studentWhere:'Open Settings, choose Accessibility, then Zoom',
    shortcut:null, lwb:false, icon:'zoom',
    ytStaff:'iPad Zoom magnification accessibility tutorial',
    ytStudent:'iPad Zoom how to make screen bigger' },

  { id:'ipad-magnifier', platform:'ipad', cats:['vision'],
    name:'Magnifier camera',
    staffDesc:'Uses iPad camera as a high-powered magnifier for real-world content. Can freeze image, adjust contrast, brightness, and colour filters. Good for reading printed materials.',
    studentDesc:'Point your iPad at anything — a worksheet, a whiteboard, a book — and zoom in to read it more easily. You can freeze the image too.',
    staffWhere:'Settings → Accessibility → Magnifier',
    studentWhere:'Open Settings, choose Accessibility, then Magnifier',
    shortcut:null, lwb:false, icon:'camera',
    ytStaff:'iPad Magnifier camera accessibility tutorial',
    ytStudent:'iPad Magnifier zoom in on real world' },

  { id:'ipad-display', platform:'ipad', cats:['vision','cognitive'],
    name:'Display and text size (iPad)',
    staffDesc:'Global display adjustments: bold text, increased contrast, reduced white point, larger text sizes. All changes apply immediately across all apps without restart.',
    studentDesc:'Make text bigger, bolder, and easier on your eyes across your whole iPad. Change it until it feels right for you.',
    staffWhere:'Settings → Accessibility → Display & Text Size',
    studentWhere:'Open Settings, choose Accessibility, then Display & Text Size',
    shortcut:null, lwb:false, icon:'type',
    ytStaff:'iPad display text size accessibility settings',
    ytStudent:'iPad make text bigger bolder settings' },

  { id:'ipad-live-captions', platform:'ipad', cats:['hearing'],
    name:'Live Captions (iPad)',
    staffDesc:'On-device real-time captioning for all audio. Works across apps — video, FaceTime, voice notes. No internet required. Text displayed as overlay at top of screen.',
    studentDesc:'Shows you what\'s being said as words on your screen in real time — for any video, voice message, or call on your iPad.',
    staffWhere:'Settings → Accessibility → Live Captions',
    studentWhere:'Open Settings, choose Accessibility, then Live Captions',
    shortcut:null, lwb:true, icon:'captions',
    ytStaff:'iPad Live Captions real-time subtitles tutorial',
    ytStudent:'iPad Live Captions how to turn on' },

  { id:'sound-recognition', platform:'ipad', cats:['hearing'],
    name:'Sound Recognition',
    staffDesc:'ML-based sound detection sends notifications for specified sounds — alarms, doorbells, sirens, baby crying, dog barking. Runs on-device.',
    studentDesc:'Your iPad listens for important sounds — like a fire alarm or a doorbell — and sends you a notification so you don\'t miss them.',
    staffWhere:'Settings → Accessibility → Sound Recognition',
    studentWhere:'Open Settings, choose Accessibility, then Sound Recognition',
    shortcut:null, lwb:false, icon:'bell',
    ytStaff:'iPad Sound Recognition accessibility notification tutorial',
    ytStudent:'iPad sound recognition alerts what is it' },

  { id:'assistive-touch', platform:'ipad', cats:['motor'],
    name:'AssistiveTouch',
    staffDesc:'Creates a customisable on-screen button that replaces physical button presses and multi-finger gestures. Fully configurable actions and menu structure.',
    studentDesc:'Adds a button to your screen that you can tap to do things that are normally hard to do physically — like pressing two buttons at once.',
    staffWhere:'Settings → Accessibility → Touch → AssistiveTouch',
    studentWhere:'Open Settings, choose Accessibility, then Touch, then AssistiveTouch',
    shortcut:null, lwb:false, icon:'touch',
    ytStaff:'iPad AssistiveTouch motor accessibility tutorial',
    ytStudent:'iPad AssistiveTouch what is it how to use' },

  { id:'switch-control', platform:'ipad', cats:['motor'],
    name:'Switch Control',
    staffDesc:'Full device operation using external adaptive switches or buttons. Auto-scanning highlights items sequentially. Enables complete iPad access with minimal physical movement.',
    studentDesc:'Control your iPad using a single button or switch instead of touching the screen. The iPad highlights things one by one and you press your switch to choose.',
    staffWhere:'Settings → Accessibility → Switch Control',
    studentWhere:'Open Settings, choose Accessibility, then Switch Control',
    shortcut:null, lwb:false, icon:'switch',
    ytStaff:'iPad Switch Control adaptive accessibility tutorial',
    ytStudent:'iPad Switch Control how does it work' },

  { id:'ipad-voice-control', platform:'ipad', cats:['motor','writing'],
    name:'Voice Control (iPad)',
    staffDesc:'Complete device control by voice. Numbered overlay on interactive elements enables precise navigation. Dictate, edit, and navigate without touching the screen.',
    studentDesc:'Say what you want to do and your iPad does it. Numbers appear on screen — say "tap 5" to press whatever is labelled 5.',
    staffWhere:'Settings → Accessibility → Voice Control',
    studentWhere:'Open Settings, choose Accessibility, then Voice Control',
    shortcut:null, lwb:true, icon:'mic',
    ytStaff:'iPad Voice Control accessibility hands free tutorial',
    ytStudent:'iPad Voice Control speak to control your iPad' },

  { id:'guided-access', platform:'ipad', cats:['cognitive'],
    name:'Guided Access',
    staffDesc:'Locks device into a single application. Can disable specific screen regions. Password or Face ID protected exit. Useful for exams, timed tasks, and SEND support.',
    studentDesc:'Locks your iPad so it stays on one app and can\'t be accidentally changed. Really useful during exams or when you need to stay focused.',
    staffWhere:'Settings → Accessibility → Guided Access',
    studentWhere:'Open Settings, choose Accessibility, then Guided Access',
    shortcut:'Triple-click top or home button', lwb:false, icon:'lock',
    ytStaff:'iPad Guided Access exam accessibility tutorial',
    ytStudent:'iPad Guided Access stay focused one app' },

  { id:'spoken-content', platform:'ipad', cats:['vision','writing','cognitive'],
    name:'Spoken Content',
    staffDesc:'Reads selected text or full screen aloud. Two-finger swipe from top to begin. Playback controls appear inline. Adjustable speed, voice, and highlight colours.',
    studentDesc:'Select any text and your iPad reads it to you. Or swipe down with two fingers to have the whole screen read aloud. Controls appear as it reads.',
    staffWhere:'Settings → Accessibility → Spoken Content',
    studentWhere:'Open Settings, choose Accessibility, then Spoken Content',
    shortcut:null, lwb:false, icon:'speaker',
    ytStaff:'iPad Spoken Content read aloud text tutorial',
    ytStudent:'iPad read text aloud to me spoken content' },

  { id:'reduce-motion-ipad', platform:'ipad', cats:['cognitive'],
    name:'Reduce Motion (iPad)',
    staffDesc:'Reduces parallax and animation effects throughout iPadOS. Important for vestibular disorders, motion sensitivity, and sensory processing differences.',
    studentDesc:'Stops your iPad from doing lots of sliding and bouncing animations. Helpful if screen movement makes you feel dizzy or uncomfortable.',
    staffWhere:'Settings → Accessibility → Motion',
    studentWhere:'Open Settings, choose Accessibility, then Motion',
    shortcut:null, lwb:false, icon:'motion',
    ytStaff:'iPad Reduce Motion sensory vestibular accessibility',
    ytStudent:'iPad stop screen animations reduce motion' },

  // ─── MICROSOFT 365 ───────────────────────────────────────────

  { id:'immersive-reader', platform:'m365', cats:['vision','writing','cognitive'],
    name:'Immersive Reader',
    staffDesc:'Multi-modal reading support embedded in Teams, Word, OneNote, Forms, and Outlook. Features: TTS with dual-highlight, syllable splitting, line focus, spacing controls, colour overlays, translation into 100+ languages. Non-stigmatising — available to all learners by default.',
    studentDesc:'Makes documents and web pages much easier to read. It reads words aloud and highlights them as it goes, lets you change the background colour, makes text bigger, and can even translate into your language.',
    staffWhere:'View → Immersive Reader (Word, OneNote, Teams)',
    studentWhere:'In Word or OneNote, tap View at the top, then Immersive Reader',
    shortcut:null, lwb:true, icon:'book',
    ytStaff:'Microsoft Immersive Reader tutorial staff FE education',
    ytStudent:'Microsoft Immersive Reader how to use students' },

  { id:'read-aloud', platform:'m365', cats:['vision','cognitive'],
    name:'Read Aloud',
    staffDesc:'TTS reading in Word, Outlook, and Edge. Highlights text synchronised with speech. Adjustable voice and speed. Available in the Review tab without additional software.',
    studentDesc:'Press play and Microsoft reads your document or email to you. It highlights each word as it reads so you can follow along.',
    staffWhere:'Review → Read Aloud (Word) · View menu (Edge)',
    studentWhere:'In Word, tap Review at the top, then Read Aloud',
    shortcut:null, lwb:false, icon:'speaker',
    ytStaff:'Microsoft Read Aloud Word Outlook tutorial',
    ytStudent:'Microsoft Word read aloud how to use' },

  { id:'dictation-m365', platform:'m365', cats:['motor','writing'],
    name:'Dictation',
    staffDesc:'Speech-to-text in Word, Outlook, and OneNote. Auto-punctuation, voice editing commands (e.g. "delete that", "new paragraph"). Available via Home tab in all three applications.',
    studentDesc:'Speak and your words appear in your document. No typing needed. It adds punctuation automatically — just talk naturally.',
    staffWhere:'Home → Dictate (Word, Outlook, OneNote)',
    studentWhere:'In Word, tap Home at the top, then Dictate',
    shortcut:null, lwb:true, icon:'mic',
    ytStaff:'Microsoft 365 Dictation speech to text tutorial staff',
    ytStudent:'Microsoft Word dictation speak to type students' },

  { id:'ms-editor', platform:'m365', cats:['writing','cognitive'],
    name:'Microsoft Editor',
    staffDesc:'AI-assisted writing support across Word, Outlook, and Edge. Grammar, spelling, clarity, conciseness, and inclusive language suggestions. Can rewrite full sentences.',
    studentDesc:'Checks your writing and suggests improvements — spelling, grammar, and whether your sentences are clear. Like having a proofreader built in.',
    staffWhere:'Home → Editor (Word) · Edge browser toolbar',
    studentWhere:'In Word, tap Home at the top, then Editor',
    shortcut:null, lwb:false, icon:'edit',
    ytStaff:'Microsoft Editor grammar spelling AI writing tutorial',
    ytStudent:'Microsoft Editor improve writing spelling grammar students' },

  { id:'translator', platform:'m365', cats:['writing'],
    name:'Translator',
    staffDesc:'Document and message translation in Word, Outlook, PowerPoint, and Teams. Supports 100+ languages. Translates selected text or full documents in place.',
    studentDesc:'Translates documents, messages, and slides into your language. Works in Word, emails, and Teams. Supports over 100 languages.',
    staffWhere:'Review → Translate (Word, PowerPoint)',
    studentWhere:'In Word, tap Review at the top, then Translate',
    shortcut:null, lwb:true, icon:'globe',
    ytStaff:'Microsoft Translator 365 ESOL multilingual tutorial',
    ytStudent:'Microsoft Translate Word document to my language' },

  { id:'live-captions-teams', platform:'m365', cats:['hearing'],
    name:'Live Captions (Teams)',
    staffDesc:'Real-time meeting subtitles in 30+ spoken languages. Can be enabled as default for all college meetings via IT admin configuration. Speaker attribution available.',
    studentDesc:'Shows you the words people are saying in your Teams call as text on screen — so you can read along with any meeting or lesson.',
    staffWhere:'Teams meeting → More options → Turn on live captions',
    studentWhere:'In a Teams call, tap More options (…) then Turn on live captions',
    shortcut:null, lwb:true, icon:'captions',
    ytStaff:'Microsoft Teams Live Captions tutorial FE staff',
    ytStudent:'Teams Live Captions how to turn on subtitles' },

  { id:'accessibility-checker', platform:'m365', cats:['vision','cognitive'],
    name:'Accessibility Checker',
    staffDesc:'Scans Word, PowerPoint, and Excel for accessibility issues: missing alt text, colour contrast failures, unlabelled tables, reading order problems. Run before every upload — it takes seconds.',
    studentDesc:'Checks your Word documents or presentations to make sure other people can read them easily, including people who use screen readers.',
    staffWhere:'Review → Check Accessibility (Word, PowerPoint, Excel)',
    studentWhere:'In Word or PowerPoint, tap Review, then Check Accessibility',
    shortcut:null, lwb:true, icon:'check',
    ytStaff:'Microsoft Accessibility Checker tutorial WCAG',
    ytStudent:'Microsoft Accessibility Checker check your document' },

  { id:'reading-progress', platform:'m365', cats:['writing','cognitive'],
    name:'Reading Progress (Teams)',
    staffDesc:'Formative reading fluency tool. Students record themselves reading assigned text. AI analyses accuracy, pace, and mispronunciations. Teacher receives report. No live monitoring pressure.',
    studentDesc:'Record yourself reading aloud and your teacher gets a report on how you\'re doing. No pressure — you can re-record if you want.',
    staffWhere:'Teams → Assignments → Add Reading Progress',
    studentWhere:'In Teams, open your Assignment and look for Reading Progress',
    shortcut:null, lwb:false, icon:'book',
    ytStaff:'Microsoft Teams Reading Progress tutorial teachers',
    ytStudent:'Teams Reading Progress record yourself reading' },

  { id:'presenter-coach', platform:'m365', cats:['cognitive','writing'],
    name:'Presenter Coach (PowerPoint)',
    staffDesc:'Real-time presentation coaching during rehearsal. Analyses pace, filler words, slide reading, and monotone delivery. Provides a detailed written report post-session.',
    studentDesc:'Practise your presentation and get feedback on how you\'re doing — are you speaking too fast? Using too many "ums"? It tells you after.',
    staffWhere:'Slide Show → Rehearse with Coach (PowerPoint)',
    studentWhere:'In PowerPoint, tap Slide Show, then Rehearse with Coach',
    shortcut:null, lwb:false, icon:'presentation',
    ytStaff:'PowerPoint Presenter Coach tutorial presentation skills',
    ytStudent:'PowerPoint Presenter Coach practise presentation feedback' },

  { id:'focus-inbox', platform:'m365', cats:['cognitive'],
    name:'Focused Inbox (Outlook)',
    staffDesc:'Filters Outlook inbox into Focused (important) and Other tabs. ML-based sorting learns from your behaviour. Reduces cognitive load for high-volume email management.',
    studentDesc:'Splits your emails into important ones and everything else, so you don\'t get overwhelmed and can find what matters quickly.',
    staffWhere:'Outlook → View → Show Focused Inbox',
    studentWhere:'In Outlook, tap View, then turn on Focused Inbox',
    shortcut:null, lwb:false, icon:'inbox',
    ytStaff:'Outlook Focused Inbox email management tutorial',
    ytStudent:'Outlook Focused Inbox manage emails students' },

  // ─── READ & WRITE (cross-platform) ───────────────────────────

  { id:'rw-text-to-speech', platform:'rw', cats:['vision','cognitive'],
    name:'Read&Write — Text to Speech',
    staffDesc:'Reads any on-screen text aloud with dual-colour word and sentence highlighting. Works in Word, Google Docs, PDFs, websites, and LMS platforms. Highly realistic AI voices. Adjustable speed and voice selection. Core tool for dyslexia, ESOL, and visual impairment support.',
    studentDesc:'Press play and Read&Write reads anything to you — documents, websites, PDFs — and highlights the words as it goes so you can follow along easily.',
    staffWhere:'Read&Write toolbar → Play button (works in Word, Google Docs, web browsers, PDFs)',
    studentWhere:'Look for the Read&Write toolbar at the top of your screen. Press the Play button to start.',
    shortcut:null, lwb:true, icon:'speaker',
    ytStaff:'Read and Write text to speech tutorial education',
    ytStudent:'Read Write how to use text to speech students' },

  { id:'rw-word-prediction', platform:'rw', cats:['writing','cognitive'],
    name:'Read&Write — Word Prediction',
    staffDesc:'Context-aware word prediction as users type. Includes phonetic prediction for dyslexic spelling patterns. Vocabulary lists with Widgit symbols. Supports 500+ topic dictionaries for subject-specific terminology.',
    studentDesc:'As you type, Read&Write suggests words you might want to use next — including ones that sound like what you\'re trying to spell. Click to insert.',
    staffWhere:'Read&Write toolbar → Word Prediction icon (in Word, Google Docs, or any text field)',
    studentWhere:'Start typing and the word suggestions will appear above what you\'re writing. Click any word to add it.',
    shortcut:null, lwb:true, icon:'edit',
    ytStaff:'Read Write word prediction dyslexia tutorial',
    ytStudent:'Read Write word prediction spelling help students' },

  { id:'rw-check-it', platform:'rw', cats:['writing'],
    name:'Read&Write — Check It',
    staffDesc:'Phonetic spellchecker that catches errors standard checkers miss — critical for dyslexic writers who spell by sound rather than rule. Also checks grammar, capitalisation, punctuation, and homophones.',
    studentDesc:'Checks your spelling the way it sounds, not just how it looks — so it catches mistakes that normal spell-check misses. Also checks grammar and punctuation.',
    staffWhere:'Read&Write toolbar → Check It button (in Word or Google Docs)',
    studentWhere:'Look for the Check It button in the Read&Write toolbar. It looks like a tick.',
    shortcut:null, lwb:true, icon:'check',
    ytStaff:'Read Write Check It phonetic spelling checker',
    ytStudent:'Read Write spelling check how to use' },

  { id:'rw-picture-dictionary', platform:'rw', cats:['writing','cognitive'],
    name:'Read&Write — Picture Dictionary',
    staffDesc:'Provides image-based word definitions. Select any word to see a picture and text definition simultaneously. Particularly effective for ESOL learners and those with limited reading vocabulary.',
    studentDesc:'Click on any word and see a picture that shows what it means. Really helpful if English isn\'t your first language or you come across words you don\'t know.',
    staffWhere:'Read&Write toolbar → Picture Dictionary icon (select a word first)',
    studentWhere:'Highlight any word, then click the Picture Dictionary button in the toolbar.',
    shortcut:null, lwb:true, icon:'camera',
    ytStaff:'Read Write picture dictionary vocabulary ESOL',
    ytStudent:'Read Write picture dictionary unknown words help' },

  { id:'rw-screen-masking', platform:'rw', cats:['vision','cognitive'],
    name:'Read&Write — Screen Masking',
    staffDesc:'Tints the screen with a coloured overlay and adds a reading strip that follows the cursor. Reduces visual stress (Meares-Irlen sensitivity). Fully customisable colour and opacity.',
    studentDesc:'Adds a colour tint to your screen and a strip that highlights the line you\'re reading. Helps if white screens hurt your eyes or if words seem to move.',
    staffWhere:'Read&Write toolbar → Screen Masking icon',
    studentWhere:'Look for the Screen Masking button in the Read&Write toolbar. It looks like a pair of glasses.',
    shortcut:null, lwb:true, icon:'eye',
    ytStaff:'Read Write screen masking visual stress Irlen tutorial',
    ytStudent:'Read Write screen masking coloured overlay how to' },

  { id:'rw-screenshot-reader', platform:'rw', cats:['vision','cognitive'],
    name:'Read&Write — Screenshot Reader',
    staffDesc:'Reads text from images and screenshots using OCR. Works on diagrams, scanned documents, images in presentations, and locked PDFs. Bridges accessibility gaps in non-text content.',
    studentDesc:'Read&Write can read the words inside images and pictures — even if you can\'t normally copy the text from them. Great for scanned documents.',
    staffWhere:'Read&Write toolbar → Screenshot Reader icon (drag over any image)',
    studentWhere:'Click the Screenshot Reader button, then drag over any image to hear it read aloud.',
    shortcut:null, lwb:false, icon:'camera',
    ytStaff:'Read Write screenshot reader OCR tutorial',
    ytStudent:'Read Write screenshot reader read text from images' },

  { id:'rw-rewordify', platform:'rw', cats:['writing','cognitive'],
    name:'Read&Write — Simplify (Rewordify)',
    staffDesc:'AI-powered text simplification. Replaces complex vocabulary and sentence structures with plainer alternatives without changing meaning. Available in Chrome/Edge extension version.',
    studentDesc:'Rewrites complicated sentences into simpler ones so they\'re easier to understand. The meaning stays the same — just in easier words.',
    staffWhere:'Read&Write toolbar → Simplify icon (Chrome/Edge extension)',
    studentWhere:'Look for the Simplify button in the Read&Write toolbar when using Chrome or Edge.',
    shortcut:null, lwb:true, icon:'type',
    ytStaff:'Read Write Rewordify simplify text tutorial',
    ytStudent:'Read Write simplify difficult text students how to' },

  { id:'rw-voice-notes', platform:'rw', cats:['motor','writing'],
    name:'Read&Write — Voice Notes',
    staffDesc:'Record voice comments inside Google Docs or Slides. Audio stored in OneDrive or Google Drive. Useful for audio feedback on student work and for students who struggle with written notes.',
    studentDesc:'Record a voice message inside a document or slide instead of typing. Good if writing is hard or you want to remember your thoughts quickly.',
    staffWhere:'Read&Write toolbar → Voice Notes icon (Google Docs/Slides or OneDrive)',
    studentWhere:'Click the Voice Notes button in the Read&Write toolbar, then speak your note.',
    shortcut:null, lwb:false, icon:'mic',
    ytStaff:'Read Write voice notes Google Docs tutorial',
    ytStudent:'Read Write voice notes record instead of typing' },

  // ─── ANDROID ─────────────────────────────────────────────────
  // Settings paths vary by manufacturer. Student descriptions acknowledge this.
  // Staff descriptions give standard Android path with Samsung variants noted.

  { id:'android-talkback', platform:'android', cats:['vision'],
    name:'TalkBack',
    staffDesc:'Android\'s built-in screen reader. Reads on-screen content aloud and navigates via swipe gestures. On Samsung devices, may appear as Voice Assistant on older versions. Works across all installed apps.',
    studentDesc:'Your Android phone reads everything on screen aloud for you — apps, messages, websites. You swipe to move between things and double-tap to open them. Depending on your phone it might be called TalkBack or Voice Assistant.',
    staffWhere:'Settings → Accessibility → TalkBack (Samsung: Accessibility → Vision → Voice Assistant)',
    studentWhere:'Open Settings, choose Accessibility, then look for TalkBack or Voice Assistant',
    shortcut:null, lwb:true, icon:'speaker',
    ytStaff:'Android TalkBack screen reader tutorial accessibility',
    ytStudent:'Android TalkBack how to use for beginners' },

  { id:'android-select-to-speak', platform:'android', cats:['vision','cognitive'],
    name:'Select to Speak',
    staffDesc:'Reads selected text or tapped screen areas aloud. Less immersive than TalkBack — the user chooses what gets read. Tap the accessibility shortcut button then tap or drag over any content. Good for learners who want targeted reading support.',
    studentDesc:'Tap the accessibility button, then tap anything on your screen to hear it read aloud. Good if you just want help reading a specific bit of text without turning on a full screen reader.',
    staffWhere:'Settings → Accessibility → Select to Speak',
    studentWhere:'Open Settings, choose Accessibility, then Select to Speak',
    shortcut:null, lwb:true, icon:'speaker',
    ytStaff:'Android Select to Speak accessibility tutorial',
    ytStudent:'Android Select to Speak read text aloud phone' },

  { id:'android-live-caption', platform:'android', cats:['hearing'],
    name:'Live Caption',
    staffDesc:'On-device real-time captions for any audio playing on the phone — video, voice messages, calls, podcasts. Works fully offline. Available on Android 10 and above. Caption window is repositionable. Present on most Android 11+ devices regardless of manufacturer.',
    studentDesc:'Shows you words on screen in real time for anything playing on your phone — videos, voice messages, calls. Works without internet. Available on most Android phones running Android 10 or newer.',
    staffWhere:'Settings → Accessibility → Live Caption (also accessible from volume controls on supported devices)',
    studentWhere:'Open Settings, choose Accessibility, then Live Caption. Or press your volume button and look for a caption icon.',
    shortcut:null, lwb:true, icon:'captions',
    ytStaff:'Android Live Caption tutorial accessibility deaf hard of hearing',
    ytStudent:'Android Live Caption how to turn on subtitles' },

  { id:'android-magnification', platform:'android', cats:['vision'],
    name:'Magnification',
    staffDesc:'Triple-tap to zoom in anywhere on the screen. Can be configured as full-screen magnification or via a dedicated shortcut button. Useful for reading small text, detailed images, or map content.',
    studentDesc:'Triple-tap your screen to zoom in anywhere. Great for reading small text or looking closely at images. Triple-tap again to zoom back out.',
    staffWhere:'Settings → Accessibility → Magnification',
    studentWhere:'Open Settings, choose Accessibility, then Magnification',
    shortcut:'Triple-tap screen', lwb:false, icon:'zoom',
    ytStaff:'Android Magnification zoom accessibility tutorial',
    ytStudent:'Android zoom in screen magnification how to' },

  { id:'android-colour-correction', platform:'android', cats:['vision'],
    name:'Colour correction',
    staffDesc:'Adjusts display colours for colour blindness. Modes: deuteranomaly (red/green), protanomaly (red/green), and tritanomaly (blue/yellow). Applied system-wide across all apps. Path varies slightly by Android version.',
    studentDesc:'Changes the colours on your screen if you find some colours hard to tell apart. Different settings for different types of colour blindness — try each one to see what helps.',
    staffWhere:'Settings → Accessibility → Colour and motion → Colour correction',
    studentWhere:'Open Settings, choose Accessibility, then Colour correction (might be inside Colour and motion)',
    shortcut:null, lwb:false, icon:'palette',
    ytStaff:'Android colour correction colour blindness accessibility',
    ytStudent:'Android colour correction colour blindness how to turn on' },

  { id:'android-colour-inversion', platform:'android', cats:['vision','cognitive'],
    name:'Colour inversion',
    staffDesc:'Inverts all display colours system-wide — white becomes black, colours are complemented. Quick way to reduce screen glare. Distinct from Dark theme (which apps must individually support).',
    studentDesc:'Flips all the colours on your screen. Great if you find bright white backgrounds harsh or painful to look at. Everything dark becomes light and vice versa.',
    staffWhere:'Settings → Accessibility → Colour and motion → Colour inversion',
    studentWhere:'Open Settings, choose Accessibility, then Colour inversion',
    shortcut:null, lwb:false, icon:'contrast',
    ytStaff:'Android colour inversion dark mode accessibility tutorial',
    ytStudent:'Android colour inversion how to turn on' },

  { id:'android-extra-dim', platform:'android', cats:['vision','cognitive'],
    name:'Extra Dim',
    staffDesc:'Reduces screen brightness beyond the standard minimum slider. Useful for light sensitivity, migraine, and low-light environments. Available on Android 12 and above. Works independently from standard brightness.',
    studentDesc:'Makes your screen even dimmer than the normal brightness slider allows. Really helpful if bright screens hurt your eyes or give you headaches. Only works on Android 12 or newer.',
    staffWhere:'Settings → Accessibility → Colour and motion → Extra Dim (Android 12+)',
    studentWhere:'Open Settings, choose Accessibility, then Extra Dim. If you don\'t see it, your phone may need an update.',
    shortcut:null, lwb:false, icon:'eye',
    ytStaff:'Android Extra Dim brightness light sensitivity accessibility',
    ytStudent:'Android Extra Dim make screen dimmer how to' },

  { id:'android-text-size', platform:'android', cats:['vision'],
    name:'Text and display size',
    staffDesc:'Increases font size and overall display density independently. Display size scales the full UI including icons and buttons; font size adjusts text rendering only. Both take effect immediately across all apps.',
    studentDesc:'Makes text, buttons, and icons bigger across your whole phone. Adjust the sliders until it feels comfortable. You can change text size and everything-else size separately.',
    staffWhere:'Settings → Accessibility → Display size and text',
    studentWhere:'Open Settings, choose Accessibility, then Display size and text',
    shortcut:null, lwb:false, icon:'type',
    ytStaff:'Android text size display size accessibility settings tutorial',
    ytStudent:'Android make text bigger font size settings' },

  { id:'android-voice-access', platform:'android', cats:['motor','writing'],
    name:'Voice Access',
    staffDesc:'Full device control by voice. Numbered overlays appear on all interactive elements — say "tap 5" to interact. Dictate text, navigate, and open apps without touching the screen. Requires Google app. May need to be downloaded from the Play Store on some devices.',
    studentDesc:'Control your whole phone with your voice — open apps, tap things, type words. Numbers appear on screen and you say the number to choose. Say "tap 3" to press whatever is labelled 3. Free to download from the Play Store if it\'s not already on your phone.',
    staffWhere:'Settings → Accessibility → Voice Access (install from Play Store if not present)',
    studentWhere:'Open Settings, choose Accessibility, then Voice Access. If it\'s not there, search "Voice Access" in the Play Store — it\'s free.',
    shortcut:null, lwb:true, icon:'mic',
    ytStaff:'Android Voice Access hands free control accessibility tutorial',
    ytStudent:'Android Voice Access speak to control your phone' },

  { id:'android-switch-access', platform:'android', cats:['motor'],
    name:'Switch Access',
    staffDesc:'Full device navigation using external adaptive switches, keyboard keys, or a single button. Scans through interactive elements sequentially. Configure scan method, speed, and switch assignment in settings. Essential for learners with significant motor impairments.',
    studentDesc:'Control your Android phone using a single button or external switch instead of touching the screen. Your phone highlights things one by one and you press your switch to choose.',
    staffWhere:'Settings → Accessibility → Switch Access',
    studentWhere:'Open Settings, choose Accessibility, then Switch Access',
    shortcut:null, lwb:false, icon:'switch',
    ytStaff:'Android Switch Access adaptive switch motor accessibility tutorial',
    ytStudent:'Android Switch Access how does it work' },

  { id:'android-sound-notifications', platform:'android', cats:['hearing'],
    name:'Sound Notifications',
    staffDesc:'Detects environmental sounds — alarms, doorbells, sirens, baby crying, running water — and sends visual notifications or vibration. Available natively on Pixel devices; other Android devices can install the Sound Notifications app free from the Play Store.',
    studentDesc:'Your phone listens for important sounds around you — like a fire alarm or doorbell — and sends a notification so you don\'t miss them. Some phones have this built in; others need a free app from the Play Store.',
    staffWhere:'Settings → Accessibility → Sound Notifications (Pixel native) or install Sound Notifications from Play Store',
    studentWhere:'Open Settings, choose Accessibility, then Sound Notifications. If it\'s not there, search "Sound Notifications" in the Play Store.',
    shortcut:null, lwb:false, icon:'bell',
    ytStaff:'Android Sound Notifications accessibility deaf hard of hearing',
    ytStudent:'Android sound alerts notifications hearing accessibility' },

  { id:'android-reduce-animations', platform:'android', cats:['cognitive'],
    name:'Remove animations',
    staffDesc:'Disables system transition and window animations. On Android 12+ accessible via Settings → Accessibility → Remove animations. On older versions requires enabling Developer Options (tap Build Number seven times in About Phone), then set Window/Transition/Animator scale to Off.',
    studentDesc:'Stops the sliding and fading effects when you switch between apps. Helpful if screen movement makes you feel dizzy or uncomfortable. Look in Accessibility settings — if you can\'t find it, ask for help.',
    staffWhere:'Settings → Accessibility → Remove animations (Android 12+) or Developer Options → set all animation scales to Off',
    studentWhere:'Open Settings, choose Accessibility, then Remove animations or Reduce motion. If you can\'t find it, ask a member of staff.',
    shortcut:null, lwb:false, icon:'motion',
    ytStaff:'Android remove animations reduce motion accessibility tutorial',
    ytStudent:'Android stop screen animations motion sensitivity' },

  { id:'android-reading-mode', platform:'android', cats:['vision','cognitive'],
    name:'Reading Mode',
    staffDesc:'Reformats web and document content into a clean, distraction-free reading layout. Adjustable font, size, spacing, and background colour. Available natively on Pixel devices and some Samsung devices. Comparable to Safari Reader View or Edge Immersive Reader.',
    studentDesc:'Turns busy web pages into a clean, simple layout that\'s much easier to read. You can change the font, background colour, and text size. Available on some phones — mainly Google Pixel and Samsung.',
    staffWhere:'Tap the Reading Mode icon in Chrome address bar (Pixel) or Settings → Accessibility → Reading Mode (Samsung One UI)',
    studentWhere:'When reading a web page, look for a book icon in your browser bar. On Samsung: open Settings, choose Accessibility, then Reading Mode.',
    shortcut:null, lwb:true, icon:'book',
    ytStaff:'Android Reading Mode accessibility dyslexia readability tutorial',
    ytStudent:'Android Reading Mode easier reading web pages how to' },

];
